################################################################################
# absorption-gradient.toml
# Three layers with absorption gradient: low → medium → high.
# Demonstrates depth-dependent energy deposition profiles.
# Lengths are in cm; mua and mus are in 1/cm.
################################################################################

[general]
photons = 300
voxel_size = 0.1

[source]
position = [0.0, 0.25, 0.0]
direction = [0, -1, 0]

# Low absorption layer (top)
[[layer]]
eta = 1.35
mua = 0.2     # Low absorption
mus = 15
ani = 0.7

vertices = [
    [-0.6,  0.2,  0.6],
    [ 0.6,  0.2,  0.6],
    [ 0.6,  0.0,  0.6],
    [-0.6,  0.0,  0.6],
    [-0.6,  0.2, -0.6],
    [ 0.6,  0.2, -0.6],
    [ 0.6,  0.0, -0.6],
    [-0.6,  0.0, -0.6]
]

faces = [
    [0, 3, 2], [0, 2, 1], [4, 5, 6], [4, 6, 7],
    [4, 7, 3], [4, 3, 0], [1, 2, 6], [1, 6, 5],
    [0, 1, 5], [0, 5, 4], [2, 3, 7], [2, 7, 6]
]

normals = [
    [ 0, 0, 1], [ 0, 0, 1], [ 0, 0, -1], [ 0, 0, -1],
    [-1, 0, 0], [-1, 0, 0], [ 1, 0, 0], [ 1, 0, 0],
    [ 0, 1, 0], [ 0, 1, 0], [ 0, -1, 0], [ 0, -1, 0]
]

# Medium absorption layer (middle)
[[layer]]
eta = 1.4
mua = 1.0     # Medium absorption
mus = 12
ani = 0.5

vertices = [
    [-0.6,  0.0,  0.6],
    [ 0.6,  0.0,  0.6],
    [ 0.6, -0.2,  0.6],
    [-0.6, -0.2,  0.6],
    [-0.6,  0.0, -0.6],
    [ 0.6,  0.0, -0.6],
    [ 0.6, -0.2, -0.6],
    [-0.6, -0.2, -0.6]
]

faces = [
    [0, 3, 2], [0, 2, 1], [4, 5, 6], [4, 6, 7],
    [4, 7, 3], [4, 3, 0], [1, 2, 6], [1, 6, 5],
    [0, 1, 5], [0, 5, 4], [2, 3, 7], [2, 7, 6]
]

normals = [
    [ 0, 0, 1], [ 0, 0, 1], [ 0, 0, -1], [ 0, 0, -1],
    [-1, 0, 0], [-1, 0, 0], [ 1, 0, 0], [ 1, 0, 0],
    [ 0, 1, 0], [ 0, 1, 0], [ 0, -1, 0], [ 0, -1, 0]
]

# High absorption layer (bottom)
[[layer]]
eta = 1.45
mua = 3.0     # High absorption
mus = 8
ani = 0.3

vertices = [
    [-0.6, -0.2,  0.6],
    [ 0.6, -0.2,  0.6],
    [ 0.6, -0.4,  0.6],
    [-0.6, -0.4,  0.6],
    [-0.6, -0.2, -0.6],
    [ 0.6, -0.2, -0.6],
    [ 0.6, -0.4, -0.6],
    [-0.6, -0.4, -0.6]
]

faces = [
    [0, 3, 2], [0, 2, 1], [4, 5, 6], [4, 6, 7],
    [4, 7, 3], [4, 3, 0], [1, 2, 6], [1, 6, 5],
    [0, 1, 5], [0, 5, 4], [2, 3, 7], [2, 7, 6]
]

normals = [
    [ 0, 0, 1], [ 0, 0, 1], [ 0, 0, -1], [ 0, 0, -1],
    [-1, 0, 0], [-1, 0, 0], [ 1, 0, 0], [ 1, 0, 0],
    [ 0, 1, 0], [ 0, 1, 0], [ 0, -1, 0], [ 0, -1, 0]
]