################################################################################
# interface.toml
# Two stacked thick layers on top of each other to demonstrate interface energy splitting.
# Lengths are in cm; mua and mus are in 1/cm.
################################################################################

[general]
photons = 1
voxel_size = 0.1

[source]
position = [0.0, 0.2, 0.0]
direction = [0.0, -1.0, 0.0]

[[layer]]
eta = 1.33  # Water-like material
mua = 0.1
mus = 10
ani = 0.9

# Top layer (water-like)
vertices = [
    [-0.3,  0.0,  0.3],  # left-top-front
    [ 0.3,  0.0,  0.3],  # right-top-front
    [ 0.3, -0.2,  0.3],  # right-bottom-front
    [-0.3, -0.2,  0.3],  # left-bottom-front
    [-0.3,  0.0, -0.3],  # left-top-rear
    [ 0.3,  0.0, -0.3],  # right-top-rear
    [ 0.3, -0.2, -0.3],  # right-bottom-rear
    [-0.3, -0.2, -0.3]   # left-bottom-rear
]

# faces (counter-clockwise vertex indices for outward normals)
faces = [
    [0, 3, 2],  # front face triangle 1
    [0, 2, 1],  # front face triangle 2
    [4, 5, 6],  # back face triangle 1
    [4, 6, 7],  # back face triangle 2
    [4, 7, 3],  # left face triangle 1
    [4, 3, 0],  # left face triangle 2
    [1, 2, 6],  # right face triangle 1
    [1, 6, 5],  # right face triangle 2
    [0, 1, 5],  # top face triangle 1
    [0, 5, 4],  # top face triangle 2
    [2, 3, 7],  # bottom face triangle 1
    [2, 7, 6]   # bottom face triangle 2
]

# normals (same order as faces)
normals = [
    [ 0,  0,  1],  # front
    [ 0,  0,  1],
    [ 0,  0, -1],  # rear
    [ 0,  0, -1],
    [-1,  0,  0],  # left
    [-1,  0,  0],
    [ 1,  0,  0],  # right
    [ 1,  0,  0],
    [ 0,  1,  0],  # top
    [ 0,  1,  0],
    [ 0, -1,  0],  # bottom
    [ 0, -1,  0]
]

[[layer]]
eta = 1.50  # Different refractive index - will cause interface splitting
mua = 0.2
mus = 20
ani = 0.8

# Bottom layer (higher refractive index)
vertices = [
    [-0.3, -0.2,  0.3],  # left-top-front
    [ 0.3, -0.2,  0.3],  # right-top-front
    [ 0.3, -0.6,  0.3],  # right-bottom-front
    [-0.3, -0.6,  0.3],  # left-bottom-front
    [-0.3, -0.2, -0.3],  # left-top-rear
    [ 0.3, -0.2, -0.3],  # right-top-rear
    [ 0.3, -0.6, -0.3],  # right-bottom-rear
    [-0.3, -0.6, -0.3]   # left-bottom-rear
]

# faces (counter-clockwise vertex indices for outward normals)
faces = [
    [0, 3, 2],  # front face triangle 1
    [0, 2, 1],  # front face triangle 2
    [4, 5, 6],  # back face triangle 1
    [4, 6, 7],  # back face triangle 2
    [4, 7, 3],  # left face triangle 1
    [4, 3, 0],  # left face triangle 2
    [1, 2, 6],  # right face triangle 1
    [1, 6, 5],  # right face triangle 2
    [0, 1, 5],  # top face triangle 1
    [0, 5, 4],  # top face triangle 2
    [2, 3, 7],  # bottom face triangle 1
    [2, 7, 6]   # bottom face triangle 2
]

# normals (same order as faces)
normals = [
    [ 0,  0,  1],  # front
    [ 0,  0,  1],
    [ 0,  0, -1],  # rear
    [ 0,  0, -1],
    [-1,  0,  0],  # left
    [-1,  0,  0],
    [ 1,  0,  0],  # right
    [ 1,  0,  0],
    [ 0,  1,  0],  # top
    [ 0,  1,  0],
    [ 0, -1,  0],  # bottom
    [ 0, -1,  0]
]