################################################################################
# pyramid.toml
# Inverted pyramid geometry with triangular faces.
# Tests non-box geometry and complex surface normals.
# Lengths are in cm; mua and mus are in 1/cm.
################################################################################

[general]
photons = 1
voxel_size = 0.05

[source]
position = [0.0, 0.2, 0.0]
direction = [0.0, -1.0, 0.0]

[[layer]]
eta = 1.37
mua = 1
mus = 10
ani = 0.0

# vertices - base at y=0, better XZ symmetry
vertices = [
    [ 0.346410,  0.0,  0.200000],
    [-0.346410,  0.0,  0.200000],
    [ 0.000000,  0.0, -0.400000],
    [ 0.0, -0.5,  0.0]
]

# faces (clockwise vertex indices)
faces = [
    [0, 1, 3],  # front
    [1, 2, 3],  # right-back
    [0, 3, 2],  # left-back
    [0, 2, 1]   # top
]

# normals (same order as faces) - computed from improved geometry
normals = [
    [ 0.000000, -0.371391,  0.928477],
    [-0.804085, -0.371391, -0.464238],
    [ 0.804085, -0.371391, -0.464238],
    [ 0.000000,  1.000000,  0.000000]
]