################################################################################
# back-scatter.toml
# Single layer with strong backward scattering (negative anisotropy).
# Shows photon backscattering and subsurface reflectance patterns.
# Lengths are in cm; mua and mus are in 1/cm.
################################################################################

[general]
photons = 300
voxel_size = 0.1

[source]
position = [0.0, 0.2, 0.0]
direction = [0, -1, 0]

[[layer]]
eta = 1.3
mua = 1.5
mus = 30
ani = -0.8    # Strong backward scattering

vertices = [
    [-0.8,  0.1,  0.8],
    [ 0.8,  0.1,  0.8],
    [ 0.8, -0.6,  0.8],
    [-0.8, -0.6,  0.8],
    [-0.8,  0.1, -0.8],
    [ 0.8,  0.1, -0.8],
    [ 0.8, -0.6, -0.8],
    [-0.8, -0.6, -0.8]
]

faces = [
    [0, 3, 2], [0, 2, 1],
    [4, 5, 6], [4, 6, 7],
    [4, 7, 3], [4, 3, 0],
    [1, 2, 6], [1, 6, 5],
    [0, 1, 5], [0, 5, 4],
    [2, 3, 7], [2, 7, 6]
]

normals = [
    [ 0,  0,  1], [ 0,  0,  1],
    [ 0,  0, -1], [ 0,  0, -1],
    [-1,  0,  0], [-1,  0,  0],
    [ 1,  0,  0], [ 1,  0,  0],
    [ 0,  1,  0], [ 0,  1,  0],
    [ 0, -1,  0], [ 0, -1,  0]
]