################################################################################
# forward-scatter.toml
# Single layer with extreme forward scattering (high positive anisotropy).
# Demonstrates ballistic vs. diffuse photon transport regimes.
# Lengths are in cm; mua and mus are in 1/cm.
################################################################################

[general]
photons = 300
voxel_size = 0.1

[source]
position = [0.0, 0.3, 0.0]
direction = [0, -1, 0]

[[layer]]
eta = 1.4
mua = 0.5
mus = 20
ani = 0.95    # Extreme forward scattering

vertices = [
    [-1.0,  0.2,  1.0],
    [ 1.0,  0.2,  1.0],
    [ 1.0, -1.5,  1.0],
    [-1.0, -1.5,  1.0],
    [-1.0,  0.2, -1.0],
    [ 1.0,  0.2, -1.0],
    [ 1.0, -1.5, -1.0],
    [-1.0, -1.5, -1.0]
]

faces = [
    [0, 3, 2], [0, 2, 1],  # front
    [4, 5, 6], [4, 6, 7],  # back
    [4, 7, 3], [4, 3, 0],  # left
    [1, 2, 6], [1, 6, 5],  # right
    [0, 1, 5], [0, 5, 4],  # top
    [2, 3, 7], [2, 7, 6]   # bottom
]

normals = [
    [ 0,  0,  1], [ 0,  0,  1],
    [ 0,  0, -1], [ 0,  0, -1],
    [-1,  0,  0], [-1,  0,  0],
    [ 1,  0,  0], [ 1,  0,  0],
    [ 0,  1,  0], [ 0,  1,  0],
    [ 0, -1,  0], [ 0, -1,  0]
]