################################################################################
# stack-3y.toml
# Three thin layers stacked vertically with different optical properties.
# Demonstrates photon transport through multiple material interfaces.
# Lengths are in cm; mua and mus are in 1/cm.
################################################################################

[general]
photons = 50
voxel_size = 0.1
log = 0
deterministic = 1

[source]
position = [0.05, 0.2, 0.05]
direction = [0, -1, 0]

[[layer]]
eta = 1.37
mua = 0.1
mus = 20
ani = 0.5

# vertices - Layer 0: Y from 0.0 to -0.1
vertices = [
    [-1.0,  0.0,  1.0],  # left-top-front
    [ 1.0,  0.0,  1.0],  # right-top-front
    [ 1.0, -0.1,  1.0],  # right-bottom-front
    [-1.0, -0.1,  1.0],  # left-bottom-front
    [-1.0,  0.0, -1.0],  # left-top-rear
    [ 1.0,  0.0, -1.0],  # right-top-rear
    [ 1.0, -0.1, -1.0],  # right-bottom-rear
    [-1.0, -0.1, -1.0]   # left-bottom-rear
]

# faces (counter-clockwise vertex indices for outward normals)
faces = [
    [0, 3, 2],  # front face triangle 1
    [0, 2, 1],  # front face triangle 2
    [4, 5, 6],  # back face triangle 1
    [4, 6, 7],  # back face triangle 2
    [4, 7, 3],  # left face triangle 1
    [4, 3, 0],  # left face triangle 2
    [1, 2, 6],  # right face triangle 1
    [1, 6, 5],  # right face triangle 2
    [0, 1, 5],  # top face triangle 1
    [0, 5, 4],  # top face triangle 2
    [2, 3, 7],  # bottom face triangle 1
    [2, 7, 6]   # bottom face triangle 2
]

# normals (same order as faces)
normals = [
    [ 0,  0,  1],  # front
    [ 0,  0,  1],
    [ 0,  0, -1],  # rear
    [ 0,  0, -1],
    [-1,  0,  0],  # left
    [-1,  0,  0],
    [ 1,  0,  0],  # right
    [ 1,  0,  0],
    [ 0,  1,  0],  # top
    [ 0,  1,  0],
    [ 0, -1,  0],  # bottom
    [ 0, -1,  0]
]

[[layer]]
eta = 1.37
mua = 1
mus = 100
ani = 0

# vertices - Layer 1: Y from -0.1 to -0.2
vertices = [
    [-1.0, -0.1,  1.0],  # left-top-front
    [ 1.0, -0.1,  1.0],  # right-top-front
    [ 1.0, -0.2,  1.0],  # right-bottom-front
    [-1.0, -0.2,  1.0],  # left-bottom-front
    [-1.0, -0.1, -1.0],  # left-top-rear
    [ 1.0, -0.1, -1.0],  # right-top-rear
    [ 1.0, -0.2, -1.0],  # right-bottom-rear
    [-1.0, -0.2, -1.0]   # left-bottom-rear
]

# faces (counter-clockwise vertex indices for outward normals)
faces = [
    [0, 3, 2],  # front face triangle 1
    [0, 2, 1],  # front face triangle 2
    [4, 5, 6],  # back face triangle 1
    [4, 6, 7],  # back face triangle 2
    [4, 7, 3],  # left face triangle 1
    [4, 3, 0],  # left face triangle 2
    [1, 2, 6],  # right face triangle 1
    [1, 6, 5],  # right face triangle 2
    [0, 1, 5],  # top face triangle 1
    [0, 5, 4],  # top face triangle 2
    [2, 3, 7],  # bottom face triangle 1
    [2, 7, 6]   # bottom face triangle 2
]

# normals (same order as faces)
normals = [
    [ 0,  0,  1],  # front
    [ 0,  0,  1],
    [ 0,  0, -1],  # rear
    [ 0,  0, -1],
    [-1,  0,  0],  # left
    [-1,  0,  0],
    [ 1,  0,  0],  # right
    [ 1,  0,  0],
    [ 0,  1,  0],  # top
    [ 0,  1,  0],
    [ 0, -1,  0],  # bottom
    [ 0, -1,  0]
]

[[layer]]
eta = 1.37
mua = 1
mus = 10
ani = -0.9

# vertices - Layer 2: Y from -0.2 to -0.3
vertices = [
    [-1.0, -0.2,  1.0],  # left-top-front
    [ 1.0, -0.2,  1.0],  # right-top-front
    [ 1.0, -0.3,  1.0],  # right-bottom-front
    [-1.0, -0.3,  1.0],  # left-bottom-front
    [-1.0, -0.2, -1.0],  # left-top-rear
    [ 1.0, -0.2, -1.0],  # right-top-rear
    [ 1.0, -0.3, -1.0],  # right-bottom-rear
    [-1.0, -0.3, -1.0]   # left-bottom-rear
]

# faces (counter-clockwise vertex indices for outward normals)
faces = [
    [0, 3, 2],  # front face triangle 1
    [0, 2, 1],  # front face triangle 2
    [4, 5, 6],  # back face triangle 1
    [4, 6, 7],  # back face triangle 2
    [4, 7, 3],  # left face triangle 1
    [4, 3, 0],  # left face triangle 2
    [1, 2, 6],  # right face triangle 1
    [1, 6, 5],  # right face triangle 2
    [0, 1, 5],  # top face triangle 1
    [0, 5, 4],  # top face triangle 2
    [2, 3, 7],  # bottom face triangle 1
    [2, 7, 6]   # bottom face triangle 2
]

# normals (same order as faces)
normals = [
    [ 0,  0,  1],  # front
    [ 0,  0,  1],
    [ 0,  0, -1],  # rear
    [ 0,  0, -1],
    [-1,  0,  0],  # left
    [-1,  0,  0],
    [ 1,  0,  0],  # right
    [ 1,  0,  0],
    [ 0,  1,  0],  # top
    [ 0,  1,  0],
    [ 0, -1,  0],  # bottom
    [ 0, -1,  0]
]